SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [Dim].[usp_ClosePastMonths]
AS
BEGIN

SET NOCOUNT ON;

UPDATE Dim.Date SET MonthIsClosed = CAST(1 AS BIT) WHERE Date <= DATEADD(DAY, -DATEPART(DAY, CURRENT_TIMESTAMP), CURRENT_TIMESTAMP);

END;
GO
